### PR TITLE
Added Lillfear

### PR DESCRIPTION
**Pull request by slushnix**
They made a skid named "Pro Swapper". They clearly took the name "Pro Swapper" and Software that was tied to the Pro Swapper Name.
image

I'll try getting into a voice call with him and get him to confess

### CODE REVIEW

**Comment by disxc** [comment]
image

**Comment by disxc** [comment]
image

**Comment by Beat-YT** [comment]
Please fix the conflicts

**Comment by lillfear** [comment]
that was not me i was hacked what the heck

**Pull request closed without merging**
