### PR TITLE
did not skid. (he is just friends with skids)

### PR DESCRIPTION
**Pull request by Ender-0001**
PS: add sparmage/twui back

### CODE REVIEW

**Comment by Beat-YT** [comment]
sus

**Comment by Beat-YT** [comment]
Fix the JSON

**Comment by realdoener** [comment]
> Fix the JSON

wdym fix the json everything is fine or do you mean the way its formatted?

**Comment by Beat-YT** [comment]
Fix the conflict

**Comment by realdoener** [comment]
> Fix the conflict

i made a new pull request

**Comment by realdoener** [comment]
what

**Comment by realdoener** [comment]
what

**Comment by Beat-YT** [comment]
You said u opened a new pr

**Pull request closed without merging**
