### PR TITLE
Added Gamotronic.

### PR DESCRIPTION
**Pull request by slushnix**
Attempted to skid Enders Gameserver and is making another skid.

Proof: https://media.discordapp.net/attachments/892812406768693319/892813316047654923/FAJhRf6VgAkuRRC.png

### CODE REVIEW

**Comment by GamotronicYT** [comment]
ok

**Comment by disxc** [comment]
Also now is trying to skid my source.

Proof: https://media.discordapp.net/attachments/892812406768693319/892813893695586344/unknown.png

**Comment by disxc** [comment]
Added everything else I needed to add

**Comment by GamotronicYT** [comment]
just what my another skid ??

**Comment by GamotronicYT** [comment]
(potato it's not me)

**Comment by disxc** [comment]
You're all on it now. so cry about it

**Comment by disxc** [comment]
Another one of the skids pathetic Screenshots. 
https://cdn.upload.systems/uploads/bYmQG2Zy.png

Please do not use any software by these bozos

**Comment by FortBloxLeaker** [comment]
@Beat-YT Please give attention to this

**Comment by Beat-YT** [comment]
?

**Pull request closed without merging**
