### PR TITLE
Aspex Skid  (skidded Aurora)

### PR DESCRIPTION
**Pull request by OraLaw**
Aspex#0002 (fexor)
image
https://github.com/ExposingPrivateServerSources/LiteNiteSources - 
image

### CODE REVIEW

**Comment by OraLaw** [comment]
image
image
More proof

**Comment by OraLaw** [comment]
Add Lecxx as skid , because he is fexor / aspex

**Comment by disxc** [comment]
Um I didn't skid anything? I didn't say that I skidded Aurora.
-_- what a good way of getting on inspect. you can even read 
all of my conversations I did not say that once

**Comment by disxc** [comment]
That Aurora Backend was used for testing. We have a new backend that is not skidded. I have worked on it for weeks. You guys are just getting pathetic at this point.

**Comment by OraLaw** [comment]
> That Aurora Backend was used for testing. We have a new backend that is not skidded. I have worked on it for weeks. You guys are just getting pathetic at this point.

The proofs there I'm just waiting for beat

**Comment by disxc** [comment]
That is not proof. You literally went on inspect element 
xD

**Comment by disxc** [comment]
You're sounding so fucking stupid right now

**Comment by OraLaw** [comment]
> That is not proof. You literally went on inspect element
> xD

But I didn't think

**Comment by disxc** [comment]
Yes it is. 
image
AND
image

were both inspect elemented.

**Comment by OraLaw** [comment]
> Yes it is.
> image
> AND
> image
> 
> were both inspect elemented.

They weren't tho

**Comment by disxc** [comment]
Yes they were
I can send all conversations right now

**Comment by disxc** [comment]
image

**Comment by disxc** [comment]
So you're telling me. You inspect elemented images. and claimed it as real. Are you fucking pathetic

**Pull request closed without merging**
