### PR TITLE
Remove doener

### PR DESCRIPTION
**Pull request by 2e4**
Hey, 

I got added to this skid list recently because I was a admin in stormfn.
I left stormfn and wanted to ask if you could remove me from the skid list now.

I'd appreciate.

### CODE REVIEW

**Comment by kayisfunne** [comment]
No

**Comment by 2e4** [comment]
bruh stfu your the biggest skid here you dont even know that you dont have to use simicolons in python :kekw:

**Comment by 2e4** [comment]
> No

bruh stfu your the biggest skid here you dont even know that you dont have to use simicolons in python :kekw:

**Comment by Beat-YT** [comment]
> I left stormfn and wanted to ask if you could remove me from the skid list now.

Im going to verify that

**Pull request closed without merging**
