### PR TITLE
Update skids.json

### PR DESCRIPTION
**Pull request by disxc**
Took myself off the skid list. I did not skid anything to be put on there. The only reason why I was "added" on the list is for exposing DrDoge for IP Logging. Bruh @Beat-YT

### CODE REVIEW

**Comment by Beat-YT** [comment]
skidded n++ and called it rift++

**Comment by disxc** [comment]
I did not skid N++. and besides I am not even in the Fortnite Modding Community @Beat-YT

**Comment by disxc** [comment]
I do not involve myself in Fortnite, I work on my own projects.

**Comment by Beat-YT** [comment]
You're vortyx

**Pull request closed without merging**
