### PR TITLE
vortyx

### PR DESCRIPTION
**Pull request by iDrDoge**

### CODE REVIEW

**Review by Beat-YT — CHANGES_REQUESTED** [review]
json spaces are changed for a skid

**Comment by iDrDoge** [comment]
wdym

**Comment by Beat-YT** [comment]
image

**Comment by iDrDoge** [comment]
spaces bro

**Comment by Beat-YT** [comment]
Fix

**Comment by iDrDoge** [comment]
I added spaces since then was that

**Comment by Beat-YT** [comment]
Fix

**Comment by iDrDoge** [comment]
I DONT KNOW

**Review by Beat-YT — APPROVED** [review]

**Comment by Beat-YT** [comment]
sorry

**Pull request merged**
