### PR TITLE
i am dumb

### PR DESCRIPTION
**Pull request by AlexDev404**
This is not abuse and not harassment to any people and is maybe against the GitHub community guidelines. I will not make sure to submit a takedown notice to this repository and all other forks associated with it. AlexDev404 is gay

### CODE REVIEW

**Comment by Beat-YT** [comment]
No

**Comment by Beat-YT** [comment]
LMFAO


skid

**Comment by Kian738** [comment]
Lmao report the list to github cuz you skidded sth

**Comment by Beat-YT** [comment]
Yes, you dumb

**Comment by HybridLeaksFN** [comment]
LOL you earned your place on that list and i doubt u will be taken off just deal with it kid your the one who skidded that was your choice now you got to suffer the consequence

**Pull request closed without merging**
