### PR TITLE
Update skids.json

### PR DESCRIPTION
**Pull request by Sparmage**
image
as seen in this image ral is a big skid

### CODE REVIEW

**Comment by ozneeeee** [comment]
> image
> as seen in this image ral is a big skid

Ral doesn't even code, I can confirm what he said in this screenshot was 100% satire, and in no way is he actually a skid!

**Comment by Sparmage** [comment]
it was a joke dumbass

**Comment by ozneeeee** [comment]
> it was a joke dumbass

You never know, your 'joke' could have been taken seriously, which wouldn't have resulted nicely.

**Comment by Sparmage** [comment]
dc

**Pull request closed without merging**
