### PR TITLE
Added a Skid

### PR DESCRIPTION
**Pull request by disxc**
Added Loxy for skidding Neonite

### CODE REVIEW

**Comment by tf-Aspex** [comment]
image
image

Him and their devs have been promoting Doxxing on the server which I believe is also against Discord ToS

**Comment by disxc** [comment]
Also added Hxdro as he is a dev with Loxy.

**Comment by OraLaw** [comment]
> Also added Hxdro as he is a dev with Loxy.

1. Feqoz not Hxdro because Feqoz made the dev for Galactic

**Comment by disxc** [comment]
But it's still skidded right?

**Comment by OraLaw** [comment]
> But it's still skidded right?

No i have the full source code but Feqoz is already there so there is no point .

**Comment by disxc** [comment]
But should I report Loxy for Breaking ToS

**Comment by OraLaw** [comment]
> But should I report Loxy for Breaking ToS

Technically yes but not to skid list to discord

**Comment by Beat-YT** [comment]
Resolve the conflict first

**Comment by OraLaw** [comment]
> Resolve the conflict first

I can tell you now there was no point in this one as there Is no solid evidence and that Hxdro and loxy don't even have PC's to code on.

**Pull request closed without merging**
